external handle_init: unit -> int = "handle_init"
external handle_free: int -> unit = "handle_free"
external in_config_session_handle: int -> bool = "in_config_session_handle"
external in_config_session: unit -> bool = "in_config_session"
external set_path: int -> string list -> int -> string = "set_path"
external delete_path: int -> string list -> int -> string = "delete_path"
